{
 "title": "Nodos",
 "time": { "from": "2024-12-15T19:59:22.698Z", "to": "2024-12-16T06:12:17.000Z" },
 "panels": [
  {
   "type": "text",
   "description": "Nodo1",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# Nodo 1 ESP32 WIRELESS STICK\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 10, "y": 0 },
   "options": {
    "content": "# Nodo 2 ESP32 WIFI LoRa V2\n\n"
   }
  },
  {
   "title": "Material Particulado 0.1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT PM01, DiaHora FROM mqttSQL.realData WHERE Nodo = 1 AND PM01 != -1;\n"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT Temperature, DiaHora FROM mqttSQL.realData WHERE Nodo = 2;\n"
    }
   ]
  },
  {
   "title": "Material Particulado 2.5",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT PM25, DiaHora FROM mqttSQL.realData WHERE Nodo = 1 AND PM01 != -1;"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT Humidity, DiaHora FROM mqttSQL.realData WHERE Nodo = 2;"
    }
   ]
  },
  {
   "title": "Material Particulado 10",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT PM10, DiaHora FROM mqttSQL.realData WHERE Nodo = 1 AND PM01 != -1;"
    }
   ]
  },
  {
   "title": "Luz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT Light, DiaHora FROM mqttSQL.realData WHERE Nodo = 2;"
    }
   ]
  },
  {
   "title": "Humedad tierra",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT Moisture, DiaHora FROM mqttSQL.realData WHERE Nodo = 1;"
    }
   ]
  },
  {
   "title": "Gas CO²",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "mqttSQL",
     "rawSql": "SELECT Gas, DiaHora FROM mqttSQL.realData WHERE Nodo = 2;\n"
    }
   ]
  }
 ]
}